import { randomBytes } from "node:crypto";
import type { File as FileModel } from "@prisma/client";
import { prisma } from "../lib/prisma";
import * as storage from "../lib/storage";
import { AppError } from "../lib/errors";

const EXT_BY_MIME: Record<string, string> = {
  "application/pdf": "pdf",
  "image/png": "png",
  "image/jpeg": "jpg",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "docx",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "xlsx",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation": "pptx",
};

/** Persists generated bytes of any supported type as a new File row (quota-checked). */
export async function saveGeneratedAny(
  userId: string,
  name: string,
  bytes: Buffer,
  mimeType: string,
  pageCount: number | null,
): Promise<FileModel> {
  const user = await prisma.user.findUniqueOrThrow({ where: { id: userId } });
  if (user.storageUsed + BigInt(bytes.length) > user.storageLimit) {
    throw new AppError(413, "QUOTA_EXCEEDED", "Not enough storage space for the result");
  }
  const ext = EXT_BY_MIME[mimeType] ?? "bin";
  const storageKey = `${userId}/${randomBytes(16).toString("hex")}.${ext}`;
  await storage.writeBytes(storageKey, bytes);

  const file = await prisma.file.create({
    data: { userId, name, mimeType, sizeBytes: BigInt(bytes.length), storageKey, pageCount },
  });
  await prisma.user.update({
    where: { id: userId },
    data: { storageUsed: { increment: BigInt(bytes.length) } },
  });
  return file;
}
