import { degrees, PDFDocument } from "pdf-lib";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { randomBytes } from "node:crypto";
import type {
  FileDTO,
  MergeInput,
  RebuildInput,
  ReplacePagesInput,
  SplitInput,
} from "@pdfforge/shared";
import type { File as FileModel } from "@prisma/client";
import { prisma } from "../lib/prisma";
import * as storage from "../lib/storage";
import * as activity from "./activity.service";
import { toFileDTO } from "./file.service";
import { AppError, badRequest, notFound } from "../lib/errors";

export async function getOwnedPdf(userId: string, fileId: string): Promise<FileModel> {
  const file = await prisma.file.findFirst({ where: { id: fileId, userId, deletedAt: null } });
  if (!file) throw notFound("File not found");
  if (file.mimeType !== "application/pdf") {
    throw badRequest(`"${file.name}" is not a PDF`, "NOT_A_PDF");
  }
  if (!storage.exists(file.storageKey)) {
    throw badRequest(`"${file.name}" is missing from storage`, "FILE_MISSING");
  }
  return file;
}

export async function loadPdf(file: FileModel): Promise<PDFDocument> {
  const bytes = await readFile(storage.resolveStorageKey(file.storageKey));
  try {
    return await PDFDocument.load(bytes, { ignoreEncryption: true });
  } catch {
    throw badRequest(`"${file.name}" could not be parsed as a PDF`, "INVALID_PDF");
  }
}

/** Persists generated PDF bytes as a new File row, enforcing the quota. */
export async function saveGenerated(
  userId: string,
  name: string,
  bytes: Uint8Array,
  pageCount: number,
): Promise<FileModel> {
  const user = await prisma.user.findUniqueOrThrow({ where: { id: userId } });
  if (user.storageUsed + BigInt(bytes.length) > user.storageLimit) {
    throw new AppError(413, "QUOTA_EXCEEDED", "Not enough storage space for the result");
  }
  await storage.ensureUserDir(userId);
  const storageKey = path.join(userId, `${randomBytes(16).toString("hex")}.pdf`);
  await writeFile(storage.resolveStorageKey(storageKey), bytes);

  const file = await prisma.file.create({
    data: {
      userId,
      name,
      mimeType: "application/pdf",
      sizeBytes: BigInt(bytes.length),
      storageKey,
      pageCount,
    },
  });
  await prisma.user.update({
    where: { id: userId },
    data: { storageUsed: { increment: BigInt(bytes.length) } },
  });
  return file;
}

/** Overwrites an existing file's contents with generated bytes. */
export async function overwrite(
  userId: string,
  file: FileModel,
  bytes: Uint8Array,
  pageCount: number,
): Promise<FileModel> {
  const delta = BigInt(bytes.length) - file.sizeBytes;
  const user = await prisma.user.findUniqueOrThrow({ where: { id: userId } });
  if (user.storageUsed + delta > user.storageLimit) {
    throw new AppError(413, "QUOTA_EXCEEDED", "Not enough storage space for the result");
  }
  await writeFile(storage.resolveStorageKey(file.storageKey), bytes);
  const updated = await prisma.file.update({
    where: { id: file.id },
    data: { sizeBytes: BigInt(bytes.length), pageCount },
  });
  await prisma.user.update({
    where: { id: userId },
    data: { storageUsed: { increment: delta } },
  });
  return updated;
}

export function withPdfExtension(name: string): string {
  return name.toLowerCase().endsWith(".pdf") ? name : `${name}.pdf`;
}

export function stripExtension(name: string): string {
  return name.replace(/\.pdf$/i, "");
}

export async function merge(userId: string, input: MergeInput): Promise<FileDTO> {
  const files: FileModel[] = [];
  for (const id of input.fileIds) files.push(await getOwnedPdf(userId, id));

  const out = await PDFDocument.create();
  for (const file of files) {
    const doc = await loadPdf(file);
    const pages = await out.copyPages(doc, doc.getPageIndices());
    for (const page of pages) out.addPage(page);
  }
  const bytes = await out.save();
  const name = withPdfExtension(input.name ?? `${stripExtension(files[0]!.name)}-merged`);
  const created = await saveGenerated(userId, name, bytes, out.getPageCount());
  await activity.log(userId, "MERGE", {
    fileId: created.id,
    detail: `${files.length} files → ${name}`,
  });
  return toFileDTO(created);
}

export async function split(
  userId: string,
  fileId: string,
  input: SplitInput,
): Promise<FileDTO[]> {
  const file = await getOwnedPdf(userId, fileId);
  const doc = await loadPdf(file);
  const total = doc.getPageCount();

  for (const range of input.ranges) {
    if (range.to > total) {
      throw badRequest(
        `Range ${range.from}-${range.to} exceeds the document (${total} pages)`,
        "RANGE_OUT_OF_BOUNDS",
      );
    }
  }

  const base = stripExtension(input.baseName ?? file.name);
  const results: FileModel[] = [];
  for (const range of input.ranges) {
    const part = await PDFDocument.create();
    const indices = Array.from({ length: range.to - range.from + 1 }, (_, i) => range.from - 1 + i);
    const pages = await part.copyPages(doc, indices);
    for (const page of pages) part.addPage(page);
    const bytes = await part.save();
    const name = `${base}-p${range.from}${range.to !== range.from ? `-${range.to}` : ""}.pdf`;
    results.push(await saveGenerated(userId, name, bytes, part.getPageCount()));
  }
  await activity.log(userId, "SPLIT", {
    fileId: file.id,
    detail: `${file.name} → ${results.length} parts`,
  });
  return results.map(toFileDTO);
}

export async function rebuild(
  userId: string,
  fileId: string,
  input: RebuildInput,
): Promise<FileDTO> {
  const file = await getOwnedPdf(userId, fileId);
  const doc = await loadPdf(file);
  const total = doc.getPageCount();

  for (const page of input.pages) {
    if (page.source !== "blank" && page.source >= total) {
      throw badRequest(
        `Page index ${page.source} exceeds the document (${total} pages)`,
        "PAGE_OUT_OF_BOUNDS",
      );
    }
  }

  const out = await PDFDocument.create();
  // Copy each referenced source page (duplicates allowed by design).
  const first = doc.getPage(0);
  const { width: defaultW, height: defaultH } = first.getSize();

  for (const spec of input.pages) {
    if (spec.source === "blank") {
      out.addPage([defaultW, defaultH]);
      continue;
    }
    const [copied] = await out.copyPages(doc, [spec.source]);
    const page = copied!;
    if (spec.rotate !== 0) {
      const current = page.getRotation().angle;
      page.setRotation(degrees((((current + spec.rotate) % 360) + 360) % 360));
    }
    out.addPage(page);
  }

  const bytes = await out.save();
  const pageCount = out.getPageCount();

  const result =
    input.mode === "replace"
      ? await overwrite(userId, file, bytes, pageCount)
      : await saveGenerated(
          userId,
          withPdfExtension(input.name ?? `${stripExtension(file.name)}-organized`),
          bytes,
          pageCount,
        );

  await activity.log(userId, "ORGANIZE", {
    fileId: result.id,
    detail: `${file.name} (${total} → ${pageCount} pages)`,
  });
  return toFileDTO(result);
}

export async function replacePages(
  userId: string,
  fileId: string,
  input: ReplacePagesInput,
): Promise<FileDTO> {
  if (input.targetPages.length !== input.sourcePages.length) {
    throw badRequest("targetPages and sourcePages must have the same length", "LENGTH_MISMATCH");
  }
  const target = await getOwnedPdf(userId, fileId);
  const source = await getOwnedPdf(userId, input.sourceFileId);
  const targetDoc = await loadPdf(target);
  const sourceDoc = await loadPdf(source);

  const targetTotal = targetDoc.getPageCount();
  const sourceTotal = sourceDoc.getPageCount();
  for (const p of input.targetPages) {
    if (p > targetTotal) {
      throw badRequest(`Target page ${p} exceeds the document (${targetTotal})`, "PAGE_OUT_OF_BOUNDS");
    }
  }
  for (const p of input.sourcePages) {
    if (p > sourceTotal) {
      throw badRequest(`Source page ${p} exceeds the document (${sourceTotal})`, "PAGE_OUT_OF_BOUNDS");
    }
  }

  const replacement = new Map<number, number>(); // target index -> source index
  input.targetPages.forEach((t, i) => replacement.set(t - 1, input.sourcePages[i]! - 1));

  const out = await PDFDocument.create();
  for (let i = 0; i < targetTotal; i += 1) {
    const sourceIdx = replacement.get(i);
    const [copied] =
      sourceIdx !== undefined
        ? await out.copyPages(sourceDoc, [sourceIdx])
        : await out.copyPages(targetDoc, [i]);
    out.addPage(copied!);
  }

  const bytes = await out.save();
  const pageCount = out.getPageCount();
  const result =
    input.mode === "replace"
      ? await overwrite(userId, target, bytes, pageCount)
      : await saveGenerated(
          userId,
          withPdfExtension(input.name ?? `${stripExtension(target.name)}-replaced`),
          bytes,
          pageCount,
        );

  await activity.log(userId, "REPLACE_PAGES", {
    fileId: result.id,
    detail: `${input.targetPages.length} pages in ${target.name} from ${source.name}`,
  });
  return toFileDTO(result);
}
